### ISSUE TITLE
Problem to install it.

### ISSUE THREAD

**Issue by margmz** [dalibo/pg_log_authfail#1]
Dear,
I would like to install pg_log_authfail but gives me the following error.  I use debian.

apt-get install build-essential
apt-get install libpq-dev
apt-get install postgresql-server-dev-8.4
# make

gcc -g -O2 -g -Wall -O2 -fPIC -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -fno-strict-aliasing -fwrapv -g -fpic -I. -I/usr/include/postgresql/8.4/server -I/usr/include/postgresql/internal -D_GNU_SOURCE -I/usr/include/libxml2  -I/usr/include/tcl8.5  -c -o pg_log_authfail.o pg_log_authfail.c
pg_log_authfail.c:53: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘**attribute**’ before ‘prev_ClientAuthentication’
pg_log_authfail.c: In function ‘_PG_init’:
pg_log_authfail.c:135: error: ‘prev_ClientAuthentication’ undeclared (first use in this function)
pg_log_authfail.c:135: error: (Each undeclared identifier is reported only once
pg_log_authfail.c:135: error: for each function it appears in.)
pg_log_authfail.c:135: error: ‘ClientAuthentication_hook’ undeclared (first use in this function)
pg_log_authfail.c: In function ‘_PG_fini’:
pg_log_authfail.c:153: error: ‘ClientAuthentication_hook’ undeclared (first use in this function)
pg_log_authfail.c:153: error: ‘prev_ClientAuthentication’ undeclared (first use in this function)
pg_log_authfail.c: In function ‘pglaf_ClientAuthentication’:
pg_log_authfail.c:166: error: ‘prev_ClientAuthentication’ undeclared (first use in this function)
pg_log_authfail.c:167: warning: implicit declaration of function ‘prev_ClientAuthentication’
make: **\* [pg_log_authfail.o] Error 1

Could you please give me a help. I'm not a programmer.

Best regards
Marcelo

**Comment by rjuju** [comment]
Hello Marcelo,

Unfortunately, this extension requires PostgreSQL 9.1 or more. I missed to mention it on the documentation, sorry for that. Also, please be aware that the 8.4 release is not supported since july 2014, so you should consider upgrading anyway.

Best regards.
